PRPC/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RegistrationUserAndLogin._2.Models;
using Stripe.Infrastructure;


namespace RegistrationUserAndLogin._2.Controllers
{
    public class MapController : Controller
    {
        public IActionResult Amarillo()
        {
            return View();
        }
        
        public IActionResult Canyon()
        {
            return View();
        }
    }
}

PRPC/Controllers/RidershipController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RegistrationUserAndLogin._2.Models;
using OneRideLib.Data;
using RegistrationUserAndLogin._2.Data;
using System.ComponentModel.DataAnnotations;

namespace RegistrationUserAndLogin._2.Controllers
{
    public class RidershipController : Controller
    {
        
        Random rnd = new Random();

        private readonly ApplicationDbContext _context;
        public IActionResult Index()
        {
            return View();
        }
        public RidershipController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult RidershipLoginButton(){
            return View();
        }
        [HttpPost]
        public IActionResult CreateBusRide(int BusID,int RiderID)
        {
            var busRideEvent = new RideEvent
            {
                //RideEventID = rideEventID,
                RiderID = RiderID,
                //BusID = BusID, for when BusID's exist
                BusID = rnd.Next(1,10),
                RideTimestamp = DateTime.Now
            };
            // await someMethodCall();
            //db.add(busRideEvent)
            return View(busRideEvent);
        }
    }
}

PRPC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegistrationUserAndLogin._2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/clickbutton.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm border-bottom box-shadow" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <h3>
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="/img/logo.png" style="padding-left:0px;">
                        </a>
                    </h3>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav navbar-nav">
                            <a type = "button" class="button2" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="dropdown">
                            <button type = "button" class="button1" data-toggle="dropdown" asp-area="" asp-controller="Home" asp-action="Privacy"><span>Map</span></button>
                                <ul class="dropdown-menu">
                                    <li><a class= "tips">Select Map:</a></li>
                                    <li><a class="nav-link" asp-controller="Map" asp-action="Amarillo">Amarillo</a></li>
                                    <li><a class="nav-link" asp-controller="Map" asp-action="Canyon">Canyon</a></li>
                                </ul>
                        </li>
                        <li class="nav navbar-nav"><a type="button" class="button2" asp-controller="Ridership" asp-action="Index">Check In (Ridership)</a></li>
                        <li class="nav navbar-nav"><a type="button" class="button2" data-toggle="modal" href="#paymentModal">Payment</a></li>
                    </ul>
                    <!-- Modal -->
                    <div class="modal fade" id="paymentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Make a Payment</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                                </div>
                                <div class="modal-body">
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label for="cardNumber">Card Number</label>
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><span class="glyphicon glyphicon-credit-card"></span></span>
                                                </div>
                                                <input type="tel" class="form-control" name="cardNumber" placeholder="Valid Card Number" autocomplete="cc-number" required autofocus />
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="form-group">
                                                    <label for="cc-exp" class="control-label mb-1">Expiration</label>
                                                    <div class="input-group">
                                                        <div class="input-group-prepend">
                                                            <div class="input-group-text">
                                                            <span class="glyphicon glyphicon-calendar"></span>
                                                            </div>
                                                        </div>
                                                        <input id="cc-exp" name="cc-exp" type="tel" class="form-control cc-exp" required placeholder="MM / YY" autocomplete="cc-exp">
                                                    </div>
                                                    
                                                    <span class="invalid-feedback">Enter the expiration date</span>
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <label for="x_card_code" class="control-label mb-1">Security code</label>
                                                <div class="input-group">
                                                    <input id="x_card_code" name="x_card_code" type="tel" class="form-control cc-cvc" required autocomplete="off">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                        <span class="glyphicon glyphicon-lock"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    <a asp-controller="Home" asp-action="PaymentReceived"><button type="button" class="btn btn-primary">Swipe Card</button></a>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; OneRide - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>